import '~/styles/globals.css';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

import tw from '~/lib/tw';
import UiProvider from '~/provider/UiProvider';

const roboto = Roboto({
   subsets: ['latin'],
   weight: ['300', '400', '500', '700', '900'],
   variable: '--font-roboto'
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={tw(roboto.variable, 'font-roboto bg-[--gray-100-color]')}>
            <NextTopLoader color='var(--blue-color)' height={2} />
            <UiProvider>{children}</UiProvider>
         </body>
      </html>
   );
}
