import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '~/styles/globals.css';
import UiProvider from '~/provider/UiProvider';
import tw from '~/lib/tw';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={tw(inter.className, 'bg-[--gray-100-color]')}>
            <UiProvider>{children}</UiProvider>
         </body>
      </html>
   );
}
